-- For user comments about a CAMPAIGN set
CREATE TABLE CAMPAIGNCOMMENT (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    CAMPAIGN INT NOT NULL,
    PERSON INT NOT NULL,
    DATETIME REAL NOT NULL,
    COMMENT TEXT NOT NULL
);

CREATE INDEX CAMPAIGNCOMMENT_INDEX ON CAMPAIGNCOMMENT(CAMPAIGN);