CREATE TABLE DETECTOR (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    INSTRUMENT INTEGER NOT NULL,
    VENDOR TEXT NOT NULL,
    MODEL TEXT NOT NULL,
    WINDOW TEXT,
    DESCRIPTION TEXT,
    UUID TEXT,
    FOREIGN KEY(INSTRUMENT) REFERENCES INSTRUMENT(PKEY)
);
