CREATE TABLE DETECTOR (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    INSTRUMENT INTEGER NOT NULL,
    VENDOR TEXT NOT NULL,
    MODEL TEXT NOT NULL,
    DESCRIPTION TEXT,
    RESOLUTION REAL,
    LLD INTEGER,
    ZERO REAL,
    GAIN REAL,
    MINK INTEGER,
    MINL INTEGER,
    MINM INTEGER,
    MINN INTEGER,
    FOREIGN KEY(INSTRUMENT) REFERENCES INSTRUMENT(PKEY)
);

INSERT INTO DETECTOR ( INSTRUMENT, VENDOR, MODEL, DESCRIPTION, RESOLUTION, LLD, ZERO, GAIN, MINK, MINL, MINM, MINN ) VALUES ( 1, "Bruker", "Quantax 6|30", "30 mm² SDD with polymer thin window", 130.0, 112, -495.0, 5.0, 4, 21, 55, 94 );
INSERT INTO DETECTOR ( INSTRUMENT, VENDOR, MODEL, DESCRIPTION, RESOLUTION, LLD, ZERO, GAIN, MINK, MINL, MINM, MINN ) VALUES ( 2, "Pulsetor", "Torrent", "30 mm² SDD - 1 of 4", 132.0, 106, 0.0, 10.0, 4, 21, 55, 94  );
INSERT INTO DETECTOR ( INSTRUMENT, VENDOR, MODEL, DESCRIPTION, RESOLUTION, LLD, ZERO, GAIN, MINK, MINL, MINM, MINN ) VALUES ( 2, "Pulsetor", "Torrent", "30 mm² SDD - 2 of 4", 132.0, 106, 0.0, 10.0, 4, 21, 55, 94  );
INSERT INTO DETECTOR ( INSTRUMENT, VENDOR, MODEL, DESCRIPTION, RESOLUTION, LLD, ZERO, GAIN, MINK, MINL, MINM, MINN ) VALUES ( 2, "Pulsetor", "Torrent", "30 mm² SDD - 3 of 4", 132.0, 106, 0.0, 10.0, 4, 21, 55, 94  );
INSERT INTO DETECTOR ( INSTRUMENT, VENDOR, MODEL, DESCRIPTION, RESOLUTION, LLD, ZERO, GAIN, MINK, MINL, MINM, MINN ) VALUES ( 2, "Pulsetor", "Torrent", "30 mm² SDD - 4 of 4", 132.0, 106, 0.0, 10.0, 4, 21, 55, 94  );
INSERT INTO DETECTOR ( INSTRUMENT, VENDOR, MODEL, DESCRIPTION, RESOLUTION, LLD, ZERO, GAIN, MINK, MINL, MINM, MINN ) VALUES ( 2, "Pulsetor", "Torrent", "30 mm² SDD - sum", 132.0, 106, 0.0, 10.0, 4, 21, 55, 94  );
