-- Header for fitting multiple spectra with a set of reference spectra.
CREATE TABLE FITSPECTRA (
   PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT,
   PROJECT INTEGER NOT NULL,
   ELEMENTS TEXT NOT NULL, -- The elements to fit (see below for format)
   FOREIGN KEY(ELEMENTS) REFERENCES ELEMENTSET(PKEY)
);

CREATE INDEX FITSPEC_PROJECT_IDX ON FITSPECTRA(PROJECT);

-- A spectrum to be fit
CREATE TABLE FITSPECTRUM (
   FITSPECTRA INT NOT NULL,
   SPECTRUM INT NOT NULL,
   SAMPLE INT NOT NULL,
   COMPOSITION INT, -- -1 or COMPOSITION.PKEY
   PRIMARY KEY(FITSPECTRA, SPECTRUM),
   FOREIGN KEY(FITSPECTRA) REFERENCES FITSPECTRA(PKEY),
   FOREIGN KEY(SPECTRUM) REFERENCES SPECTRUM(PKEY)
   FOREIGN KEY(SAMPLE) REFERENCES SAMPLE(PKEY)
);

CREATE INDEX UNK_QUANT_IDX ON FITSPECTRUM(FITSPECTRA);

-- A reference spectrum
CREATE TABLE REFERENCESPECTRUM (
   FITSPECTRA INT NOT NULL,
   SPECTRUM INT NOT NULL,
   SAMPLE INT NOT NULL,
   ELEMENTS TEXT NOT NULL, -- Elements in the material (see below for format)
   REFFOR TEXT NOT NULL,   -- Unobstructed energy intervals for which this spectrum can be a reference...
   PRIMARY KEY(FITSPECTRA, SPECTRUM),
   FOREIGN KEY(FITSPECTRA) REFERENCES FITSPECTRA(PKEY),
   FOREIGN KEY(SPECTRUM) REFERENCES SPECTRUM(PKEY),
   FOREIGN KEY(SAMPLE) REFERENCES SAMPLE(PKEY)
);
-- NOTE: It is common by not necessary to know the composition of the reference spectrum.

CREATE INDEX REF_QUANT_IDX ON REFERENCESPECTRUM(FITSPECTRA);

-- NOTE: ELEMENTS and REFFOR are stored as a string of element symbols separated by commas i.e. "Fe,Cr,Ni"
-- This is much more transparent than creating a special set of tables

-- "SELECT * FROM FITSPECTRUM WHERE FITSPECTRA=?;"
-- "SELECT * FROM REFERENCESPECTRUM WHERE FITSPECTRA=?;"
-- "INSERT INTO ELEMENT ( ELMSET, ATOMICNUMBER) VALUES (?, ?);"
