CREATE TABLE FITSPECTRUM (
   PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME TEXT,
   PROJECT INTEGER NOT NULL,
   ELEMENTS TEXT NOT NULL, -- The elements to fit
   FOREIGN KEY(ELEMENTS) REFERENCES ELEMENTSET(PKEY)
);

CREATE INDEX FITSPEC_PROJECT_IDX ON FITSPECTRUM(PROJECT);

CREATE TABLE UNKNOWNSPECTRUM (
   FITSPECTRUM INT NOT NULL,
   SPECTRUM INT NOT NULL,
   COMPOSITION INT, -- -1 or COMPOSITION.PKEY
   PRIMARY KEY(FITSPECTRUM, SPECTRUM),
   FOREIGN KEY(FITSPECTRUM) REFERENCES FITSPECTRUM(PKEY),
   FOREIGN KEY(SPECTRUM) REFERENCES SPECTRUM(PKEY)
);

CREATE INDEX UNK_QUANT_IDX ON UNKNOWNSPECTRUM(FITSPECTRUM);

CREATE TABLE REFERENCESPECTRUM (
   FITSPECTRUM INT NOT NULL,
   SPECTRUM INT NOT NULL,
   ELEMENTS TEXT NOT NULL, -- Elements in the material
   REFFOR TEXT NOT NULL,   -- Elements for which this is a reference
   PRIMARY KEY(FITSPECTRUM, SPECTRUM),
   FOREIGN KEY(FITSPECTRUM) REFERENCES FITSPECTRUM(PKEY),
   FOREIGN KEY(SPECTRUM) REFERENCES SPECTRUM(PKEY)
);

CREATE INDEX REF_QUANT_IDX ON REFERENCESPECTRUM(FITSPECTRUM);

-- "SELECT * FROM UNKNOWNSPECTRUM WHERE FITSPECTRUM=?;"
-- "SELECT * FROM REFERENCESPECTRUM WHERE FITSPECTRUM=?;"

-- "INSERT INTO ELEMENT ( ELMSET, ATOMICNUMBER) VALUES (?, ?);"
