-- A spectrum to be fit
CREATE TABLE FITSPECTRUM (
   CAMPAIGN INT NOT NULL,  -- CAMPAIGN(PKEY)
   SPECTRUM INT NOT NULL,  -- SPECTRUM(PKEY)
   FOREIGN KEY(CAMPAIGN) REFERENCES CAMPAIGN(PKEY),
   FOREIGN KEY(SPECTRUM) REFERENCES SPECTRUM(PKEY),
   PRIMARY KEY(CAMPAIGN, SPECTRUM)
);