-- For user comments about a FitSpectra set
CREATE TABLE FSCOMMENT (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    FITSPECTRA INT NOT NULL,
    PERSON INT NOT NULL,
    DATETIME REAL NOT NULL,
    COMMENT TEXT NOT NULL
);

CREATE INDEX FSCOMMENT_INDEX ON FSCOMMENT(FITSPECTRA);