CREATE TABLE INSTRUMENT (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    LABKEY INTEGER NOT NULL,
    VENDOR TEXT NOT NULL,
    MODEL TEXT NOT NULL,
    LOCATION TEXT NOT NULL,
    FOREIGN KEY(LABKEY) REFERENCES LABORATORY(PKEY)
);
