CREATE TABLE INSTRUMENT (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    LABKEY INTEGER NOT NULL,
    VENDOR TEXT NOT NULL,
    MODEL TEXT NOT NULL,
    LOCATION TEXT NOT NULL,
    FOREIGN KEY(LABKEY) REFERENCES LABORATORY(PKEY)
);

INSERT INTO INSTRUMENT ( LABKEY, VENDOR, MODEL, LOCATION ) VALUES ( 1, "JEOL", "JXA-8500F", "Building 217 D113" );
INSERT INTO INSTRUMENT ( LABKEY, VENDOR, MODEL, LOCATION ) VALUES ( 1, "TESCAN", "MIRA3", "Building 217 F101" );
