CREATE TABLE LABMEMBERS (
    LABKEY INTEGER NOT NULL,
    PERSONKEY INTEGER NOT NULL,
    FOREIGN KEY(LABKEY) REFERENCES LABORATORY(PKEY),
    FOREIGN KEY(PERSONKEY) REFERENCES PERSON(PKEY),
    PRIMARY KEY(LABKEY, PERSONKEY)
);

CREATE INDEX MEMBER_INDEX ON LABMEMBERS(PERSONKEY);

INSERT INTO LABMEMBERS ( LABKEY, PERSONKEY ) VALUES ( 1, 1 );
INSERT INTO LABMEMBERS ( LABKEY, PERSONKEY ) VALUES ( 1, 2 );
