CREATE TABLE LABMEMBER (
    LABKEY INTEGER NOT NULL,
    PERSONKEY INTEGER NOT NULL,
    FOREIGN KEY(LABKEY) REFERENCES LABORATORY(PKEY),
    FOREIGN KEY(PERSONKEY) REFERENCES PERSON(PKEY),
    PRIMARY KEY(LABKEY, PERSONKEY)
);

CREATE INDEX LABMEMBER_PERSON_INDEX ON LABMEMBER(PERSONKEY);

INSERT INTO LABMEMBER ( LABKEY, PERSONKEY ) VALUES ( 1, 1 );
INSERT INTO LABMEMBER ( LABKEY, PERSONKEY ) VALUES ( 1, 2 );
