CREATE TABLE MASSFRACTION (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    MATKEY INTEGER NOT NULL,
    MFZ INTEGER NOT NULL, -- Atomic number
    MFC REAL NOT NULL, -- Mass fraction
    MFUC REAL, -- Uncertainty in c (1 σ) or NULL if unknown
    MFA REAL, -- atomic weight or NULL if default
    FOREIGN KEY(MATROWID) REFERENCES MATERIAL(PKEY)
);

CREATE INDEX MFCZ_INDEX ON MASSFRACTION(MFZ, MFC);
CREATE INDEX MFCZ_INDEX ON MASSFRACTION(MFZ, MFC);
