CREATE TABLE MATERIAL (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    MATNAME TEXT NOT NULL, -- Make material name unique
    MATDESCRIPTION TEXT,
    MATDENSITY REAL
);

INSERT INTO MATERIAL ( MATNAME, MATDESCRIPTION, MATDENSITY ) VALUES ( "Unknown", "Unknown material", 0.0 );
CREATE INDEX MATNAME_INDEX ON MATERIAL(MATNAME);
