CREATE TABLE PERSON (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);

CREATE INDEX PERSON_EMAIL_INDEX ON PERSON (EMAIL);

INSERT INTO PERSON ( PKEY, NAME, EMAIL ) VALUES ( 1, "Nicholas Ritchie", "nicholas.ritchie@nist.gov");
INSERT INTO PERSON ( PKEY, NAME, EMAIL ) VALUES ( 2, "Dale Newbury", "dale.newbury@nist.gov");
