CREATE TABLE PROJECT (
    PKEY INTEGER PRIMAY KEY NOT NULL,
    PARENT INTEGER,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT
);

INSERT INTO PROJECT ( PARENT, NAME, DESCRIPTION ) VALUES ( -1, "K-ratio Project", "Community Consensus K-ratio Project");
