CREATE TABLE PROJECT (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    PARENT INTEGER,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT
);

CREATE INDEX PROJECT_PARENT_IDX ON PROJECT(PARENT);
CREATE INDEX PROJECT_NAME_IDX ON PROJECT(NAME);

INSERT INTO PROJECT ( PKEY, PARENT, NAME, DESCRIPTION ) VALUES ( 0, 0, "Root", "Root Project" );
INSERT INTO PROJECT ( PARENT, NAME, DESCRIPTION ) VALUES ( 0, "K-ratio Project", "Community Consensus K-ratio Project");
