CREATE TABLE BLOCK (
    LABROWID INTEGER NOT NULL,
    NAME TEXT NOT NULL, -- Ex: "Block C"
    DESCRIPTION TEXT,
    FOREIGN KEY(LABROWID) REFERENCES LABORATORY(ROWID)
    PRIMARY KEY(LABROWID, NAME)
);

CREATE TABLE STANDARD
    BLOCKROWID INTEGER NOT NULL
    MATROWID INTEGER NOT NULL, -- material(pkey)
    FOREIGN KEY(MATROWID) REFERENCES MATERIAL(ROWID),
    FOREIGN KEY(BLOCKROWID) REFERENCES BLOCK(ROWID),
);
