-- DEFINES A SPECTRUM FROM MATERIAL COLLECTED ON A DETECTOR
CREATE TABLE SPECTRUM (
    PKEY INTEGER PRIMARY KEY AUTOINCREMENT,
    DETECTOR INTEGER NOT NULL, -- Need to know the detector ()
    BEAMENERGY REAL NOT NULL, -- IN EV
    COMPOSITION INTEGER,  -- -1 for unknown
    COLLECTEDBY INTEGER NOT NULL,  -- PERSON(PKEY)
    SAMPLE INTEGER NOT NULL, -- SAMPLE(PKEY)
    COLLECTED TIMESTAMP,
    NAME TEXT,
    UUID TEXT,
    FOREIGN KEY(DETECTOR) REFERENCES DETECTOR(PKEY),
    FOREIGN KEY(COMPOSITION) REFERENCES MATERIAL(PKEY),
    FOREIGN KEY(COLLECTEDBY) REFERENCES PERSON(PKEY),
    FOREIGN KEY(SAMPLE) REFERENCES SAMPLE(PKEY)
);
